apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: basic-auth
  namespace: observability
data:
  auth: YWRtaW46JGFwcjEkYzZlQURWWmEkQk5qcDhTQ2FNanVVMmFMbnF2ZnZsMAoK
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prm-ingress
  namespace: observability
  annotations:
    cert-manager.io/issuer: issuer-do
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: 50M
spec:
  tls:
  - hosts:
    - prm.growbe.ca
  rules:
  - host: prm.growbe.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-operated
            port:
              number: 9090