apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: frontend-dev
  name: frontend-dev
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
  selector:
    io.kompose.service: frontend-dev
status:
  loadBalancer: {}
