apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  ports:
  - name: "27018"
    port: 27018
    targetPort: 27018
  selector:
    io.kompose.service: mongo
status:
  loadBalancer: {}
