apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: growbe-cloud
  name: growbe-cloud-releases
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
status: {}
