# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


cloud:
  # Version of the growbe-cloud application to deploy
  version: 1.0.0
  # Name of the environment you are deploying
  env: dev
  # Base domain name for the site , all component will be routed to subdomain
  basePath: growbe.ca
  http:
    # This secret need to be manually created to be able to create certificate
    certSecret: tls-growbedev
  # Use for the mqtt service that run as a NodeService
  externalIP: 192.168.2.1

  broker:
    port: 1883
    portws: 9001

  confgenerator:
    gh_pat: xxxxxx
    id_rsa: xxxxxx

  nms:
    enabled: true
    auth:
      username: testadmin
      password: 123345678

  mongo:
    auth:
      username: doadmin
      password: test
  pgsql:
    auth:
      username: test
      password: test
  sso:
    email:
      auth:
        username: apikey
        password: xxxxxx
      from: '"Growbe Cloud" <robot@growbe.ca>'
      redirect: https://cloud.dev.growbe.ca
    settings: '{"publicCreation":true,"multiFactor":false,"accountValidation":true, "defaultRoles": []}'
    secret:
      otp: 123456
      jwt: 2342tf
