apiVersion: v1
kind: Secret
metadata:
  name: growbe-cloud
type: Opaque
data:
  DB_URL: postgres://{{ .Values.cloud.pgsql.auth.username }}:{{ .Values.cloud.pgsql.auth.password }}@pgsql:5432/defaultdb
  MONGO_URL: mongodb://{{ .Values.cloud.mongo.auth.username }}:{{ .Values.cloud.mongo.auth.password }}@mongo:27018/growbe?authSource=admin
  NMS_API_USERNAME: {{ .Values.cloud.nms.auth.username | squote}}
  NMS_API_PASSWORD: {{ .Values.cloud.nms.auth.password | squote}}
  NMS_TOKEN: {{ .Values.cloud.nms.auth.token | squote}}
  GITHUB_TOKEN_RO: {{ .Values.cloud.confgenerator.gh_pat | squote}}
  REVERSE_PROXY_ID_RSA: {{ .Values.cloud.confgenerator.id_rsa | squote}}