apiVersion: v1
kind: Secret
metadata:
  name: mongo 
type: Opaque
data:
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.cloud.mongo.auth.password | squote}}
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.cloud.mongo.auth.username | squote}}