apiVersion: v1
kind: Secret
metadata:
  name: nms
type: Opaque
data:
  NMS_API_PASSWORD: {{ .Values.cloud.nms.auth.password | squote}}
  NMS_API_USERNAME: {{ .Values.cloud.nms.auth.username | squote}}
  NMS_TOKEN: {{ .Values.cloud.nms.auth.token | squote }}