apiVersion: v1
kind: Secret
metadata:
  name: pgsql
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.cloud.pgsql.auth.username | squote }}
  POSTGRES_USER: {{ .Values.cloud.pgsql.auth.password | squote }}