apiVersion: v1
kind: Secret
metadata:
  name: sso
type: Opaque
stringData:
  EMAIL_PASSWORD: {{ .Values.cloud.sso.email.auth.password | squote }}
  EMAIL_USER: {{ .Values.cloud.sso.email.auth.username | squote }}
  JWT_SECRET: {{ .Values.cloud.sso.secret.jwt | squote }}
  OTP_SECRET: {{ .Values.cloud.sso.secret.otp | squote }}
  DB_URL: postgres://{{ .Values.cloud.pgsql.auth.username }}:{{ .Values.cloud.pgsql.auth.password }}@pgsql:5432/defaultdb
