apiVersion: v1
kind: Secret
metadata:
  name: growbe-cloud-watcher
type: Opaque
data:
  DB_URL: postgres://{{ .Values.cloud.pgsql.auth.username }}:{{ .Values.cloud.pgsql.auth.password }}@pgsql:5432/defaultdb
  MONGO_URL: mongodb://{{ .Values.cloud.mongo.auth.username }}:{{ .Values.cloud.mongo.auth.password }}@mongo:27018/growbe?authSource=admin