apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: broker
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: broker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: broker
    spec:
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: ghcr.io/growbe2/growbe-cloud/broker:latest
        imagePullPolicy: Always
        name: broker
        ports:
        - containerPort: 1883
          protocol: TCP
        - containerPort: 9001
          protocol: TCP
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ghcr
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
status: {}