# TODO : need to support the tcp ingress with the service instead of the node port
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: broker
  name: broker
spec:
  ports:
  - name: {{ .Values.cloud.broker.port | quote }}
    port: {{ .Values.cloud.broker.port }}
    targetPort: 1883
  - name: {{ .Values.cloud.broker.portws | quote }}
    port: {{ .Values.cloud.broker.portws }}
    targetPort: 9001
  selector:
    io.kompose.service: broker
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: broker-node
  name: broker-node
spec:
  type: NodePort
  ports:
  - name: {{ .Values.cloud.broker.port | quote }}
    port: {{ .Values.cloud.broker.port }}
    targetPort: 1883
    nodePort: 30045
    protocol: TCP
  selector:
    io.kompose.service: broker
status:
  loadBalancer: {}
