# TODO : need to support the tcp ingress with the service instead of the node port
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: broker
  name: broker
spec:
  ports:
  - name: '1883'
    port: 1883
    targetPort: 1883
  - name: '9001'
    port: 9001
    targetPort: 9001
  selector:
    io.kompose.service: broker
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: broker-node
  name: broker-node
spec:
  type: NodePort
  ports:
  - name: '1883'
    port: 1883
    targetPort: 1883
    nodePort: {{ .Values.cloud.broker.port }}
    protocol: TCP
  selector:
    io.kompose.service: broker
status:
  loadBalancer: {}
