apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: conf-server
  name: conf-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: conf-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: conf-server
    spec:
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
      - image: ghcr.io/growbe2/growbe-cloud/config-{{ .Values.cloud.env }}:latest
        imagePullPolicy: Always
        name: conf-server
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ghcr
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}