apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: frontend-dev
  name: frontend-dev
spec:
  {{- with .Values.deployment.affinity }}
  affinity:
    {{- toYaml . | nindent 8 }}
  {{- end }}

  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend-dev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: frontend-dev
    spec:
      containers:
      - image: ghcr.io/growbe2/growbe-cloud/growbe-portal:{{ .Values.cloud.version }}
        imagePullPolicy: Always
        name: frontend-dev
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ghcr
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}