apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: growbe-cloud-watcher
  name: growbe-cloud-watcher
spec:
  selector:
    matchLabels:
      io.kompose.service: growbe-cloud-watcher
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: growbe-cloud-watcher
    spec:
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
      - args:
        - node
        - dist/growbe-watcher.js
        env:
        - name: MQTT_URL
          value: mqtt://broker:1883
        - name: PORT
          value: "3005"
        - name: SSO_URL
          value: http://sso:3001
        - name: DEBUG
          value: 'growbe:*'
        - name: TZ
          value: "America/Toronto"
        envFrom:
        - secretRef:
            name: growbe-cloud-watcher
        image: ghcr.io/growbe2/growbe-cloud/growbe-cloud:{{ .Values.cloud.version }}
        name: growbe-cloud-watcher
        ports:
        - name: http
          containerPort: 3005
          protocol: TCP
        resources: {}
        #livenessProbe:
        #  httpGet:
        #    path: /live
        #    port: http
        #  failureThreshold: 1
        #  initialDelaySeconds: 5
        #  periodSeconds: 3
        #readinessProbe:
        #  httpGet:
        #    path: /ready
        #    port: http
        #  failureThreshold: 1
        #  initialDelaySeconds: 5
        #  periodSeconds: 3
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ghrc
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
status: {}
