apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: growbe-cloud-watcher
  name: growbe-cloud-watcher
spec:
  selector:
    matchLabels:
      io.kompose.service: growbe-cloud-watcher
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: growbe-cloud-watcher
    spec:
      containers:
      - args:
        - node
        - dist/growbe-watcher.js
        env:
        - name: DB_URL
          value: postgres://{{ .Values.cloud.pgsql.auth.username }}:{{ .Values.cloud.pgsql.auth.password }}@pgsql:5432/defaultdb
        - name: MONGO_URL
          value: mongodb://{{ .Values.cloud.mongo.auth.username }}:{{ .Values.cloud.mongo.auth.password }}@mongo:27018/growbe?authSource=admin
        - name: MQTT_URL
          value: mqtt://broker:{{ .Values.cloud.broker.port }}
        - name: PORT
          value: "3005"
        - name: SSO_URL
          value: http://sso:3001
        - name: DEBUG
          value: 'growbe:*'
        - name: TZ
          value: "America/Toronto"
        image: ghcr.io/growbe2/growbe-cloud/growbe-cloud:{{ .Values.cloud.version }}
        imagePullPolicy: Always
        name: growbe-cloud-watcher
        ports:
        - name: http
          containerPort: 3005
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        livenessProbe:
          httpGet:
            path: /live
            port: http
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 3
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ghrc
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
status: {}
