apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: growbe-cloud
  name: growbe-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: growbe-cloud
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: growbe-cloud
    spec:
      containers:
      - args:
        - node
        - dist/growbe-cloud.js
        env:
        - name: MQTT_URL
          value: mqtt://broker:{{ .Values.cloud.broker.port }}
        - name: NMS_API_URL
          value: http://nms:8000
        - name: PORT
          value: "3000"
        - name: SSO_URL
          value: http://sso:3001
        - name: DEBUG
          value: growbe:*
        - name: TZ
          value: "America/Toronto"
        envFrom:
        - secretRef:
            name: growbe-cloud
        image: ghcr.io/growbe2/growbe-cloud/growbe-cloud:{{ .Values.cloud.version }}
        name: growbe-cloud
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        resources: {}
        #livenessProbe:
        #  httpGet:
        #    path: /live
        #    port: http
        #  failureThreshold: 1
        #  initialDelaySeconds: 5
        #  periodSeconds: 3
        #readinessProbe:
        #  httpGet:
        #    path: /ready
        #    port: http
        #  failureThreshold: 1
        #  initialDelaySeconds: 5
        #  periodSeconds: 3
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ghrc
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
status: {}
