apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: growbe-cloud-proxy-cmd
  name: growbe-cloud-proxy-cmd
spec:
  ports:
  - name: "3008"
    port: 3008
    targetPort: http
  selector:
    io.kompose.service: growbe-cloud-proxy-cmd
status:
  loadBalancer: {}
