apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongo
    spec:
      containers:
      - args:
        - mongod
        - --port
        - "27018"
        env:
        - name: MONGO_INITDB_DATABASE
          value: growbe
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: {{ .Values.cloud.mongo.auth.password }}
        - name: MONGO_INITDB_ROOT_USERNAME
          value: {{ .Values.cloud.mongo.auth.username }}
        image: mongo
        imagePullPolicy: Always
        name: mongo
        ports:
        - containerPort: 27018
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/db
          name: mongo
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mongo
        persistentVolumeClaim:
          claimName: mongo
status: {}