{{- if eq .Values.cloud.prometheus.enable true }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: growbe-service-monitor
  labels:
    prometheus-monitor: "true"
spec:
  selector:
    matchLabels:
      growbe: service
  endpoints:
    - targetPort: http
      scheme: http
      path: '/metrics'
      interval: 10s
      honorLabels: true
  namespaceSelector:
    any: true
{{end}}