apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: sso
  name: sso
spec:
  {{- with .Values.deployment.affinity }}
  affinity:
    {{- toYaml . | nindent 8 }}
  {{- end }}

  selector:
    matchLabels:
      io.kompose.service: sso
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sso
    spec:
      containers:
      - args:
        - npm
        - run
        - start
        env:
        - name: EMAIL_FROM
          value: {{ .Values.cloud.sso.email.from | squote }} 
        - name: EMAIL_REDIRECT
          value: {{ .Values.cloud.sso.email.redirect }}
        - name: JWT_TTL
          value: "9600"
        - name: PORT
          value: "3001"
        - name: TZ
          value: "America/Toronto"
        - name: SMS_NUMBER
        - name: SMS_SID
        - name: SMS_TOKEN
        - name: SSO_SETTINGS
          value: {{ .Values.cloud.sso.settings | squote}}
        envFrom:
        - secretRef:
            name: sso
        image: ghcr.io/growbe2/growbe-cloud/sso:latest
        imagePullPolicy: Always
        name: sso
        ports:
        - containerPort: 3001
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ghcr
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
