on:
  push:
    branches:
      - main


name: Release chart

jobs:
  proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install helm
        uses: Azure/setup-helm@v1
      - name: login to acr using helm
        run: |
          echo ${{ secrets.PAT }} | helm registry login ${{ env.GCR_IMAGE }} --username berlingoqc --password-stdin
        env:
          GCR_IMAGE: ghcr.io/growbe2/public-cloud
      - name: package chart
        run: ./bundle_repo.sh
      - name: Release archive to latest
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest tarball of the charts"
          files: |
            ./output/*
