on:
  push:
    branches:
      - main


name: Release chart

jobs:
  proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install helm
        uses: Azure/setup-helm@v1
      - name: login to acr using helm
        run: |
          echo ${{ secrets.PAT }} | helm registry login ${{ env.GCR_IMAGE }} --username berlingoqc --password-stdin
        env:
          GCR_IMAGE: ghcr.io/growbe2/public-cloud
      - name: package chart
        run: |
          helm package ./helm/growbe-cloud && helm package ./helm/growbe-cloud-secrets
      - name: publish chart to acr
        run: |
          helm push $(ls growbe-cloud-chart-*) oci://ghcr.io/growbe2/
          helm push $(ls growbe-cloud-secret*) oci://ghcr.io/growbe2/
        env:
          GCR_IMAGE: ghcr.io/growbe2/public-cloud
